### ISSUE TITLE
SVXLINK Connect/disconnet command #

### ISSUE THREAD

**Issue by astro9600** [sm0svx/svxlink#195]
Hi, I would like to change the connect/disconnect command if possible.

Insteaad using the #.

Can I do; connect *7 and disconnect #9

Thank you

**Comment by sm0svx** [comment]
Yes you now can but you need some TCL coding skills to do it. In latest Git master there is a new TCL function called injectDtmf (e.g. injectDtmf "1234#") that can be used in conjunction with the dtmf_digit_received and dtmf_cmd_received functions in Logic.tcl to remap DTMF commands. One should be very careful when doing this since you can easily break things.
