### ISSUE TITLE
segfault error metainfo

### ISSUE THREAD

**Issue by kb3vgw** [sm0svx/svxlink#234]
/usr/src/svxlink-build/svxlink-15.99/src/svxlink/modules/metarinfo/ModuleMetarInfo.cpp: In member function ‘std::string ModuleMetarInfo::getLightning(std::string)’:
/usr/src/svxlink-build/svxlink-15.99/src/svxlink/modules/metarinfo/ModuleMetarInfo.cpp:1257:13: internal compiler error: Segmentation fault
 std::string ModuleMetarInfo::getLightning(std::string token)
             ^
Please submit a full bug report,
with preprocessed source if appropriate.

**Comment by sm0svx** [comment]
SvxLink cannot be blamed for an internal error in the compiler. Please report the problem to the gcc project or the package maintainer for your distribution. Maybe the problem has been fixed in a later version of the compiler.

Maybe try to reinstall the operating system just in case some files have been corrupted for some reason.
