### ISSUE TITLE
Remote audio delay

### ISSUE THREAD

**Issue by JimZAH** [sm0svx/svxlink#418]
Hi Chaps,

Firstly may I say thank you to SM0SVX for such a great project. I've been using SVXLink on the UHF repeater GB3JC for many years now.

I'm working on a big project (not as big as PI2NOS!) but it's big for the UK at least. I'm currently linking systems together using the voting features. 

I have a main server that runs the logic and repeaters on different sites. Now I know there has always been a little audio delay 100ms for eg. Sometimes the audio seems to lag 500ms which means users hear there last word(s) when dekeying.

I understand the connections can cause this, my question is: what can be done (if any) to lower the delay? I've disabled 1750Hz/DTMF muting.

The SVXLink server is running on KVM. The repeaters use RPI3.

Kind Regards
James Colderwood
M0ZAH

**Comment by sm0svx** [comment]
Please use the [SourceForge mailing lists](https://sourceforge.net/p/svxlink/mailman/svxlink-devel/) or [groups.io](https://groups.io/g/svxlink) to ask questions.

It is a known problem that delays can be long from time to time when using RemoteTrx. I do not have an immediate cure for this at this moment. Using UDP instead of TCP for audio transfer could help but that requires some coding of course.
