### ISSUE TITLE
GPIO Problems...

### ISSUE THREAD

**Issue by George-L** [sm0svx/svxlink#491]
Hello! I just installed SVXLink on my Raspberry Pi3B+ and I can't get the GPIO to work. 

I get these errors.

Failed to start SvxLink repeater control software GPIO setup

svxlink_gpio_up[1206]: chown: cannot access '/sys/class/gpio/17/value': No such file or directory

I checked and gpio17 folder is in /sys/class/gpio with the value file in the folder gpio17.  I am doing something wrong, but I dont know what.

Thanks for the help and 73 de YO2LIG,

**Comment by sm0svx** [comment]
Hi George,

This is not a support forum. You should use [groups.io](https://groups.io/g/svxlink) to ask questions like this. The issue tracker is used for reporting bugs and requesting features.

But anyway, you probably have just set the wrong value for the GPIO_SQL_PIN configuration variable. Looks like you have set it to "17" instead of "gpio17".
