### ISSUE TITLE
UDP Stream in TX 

### ISSUE THREAD

**Issue by sp2ong** [sm0svx/svxlink#511]
I'm working on a solution that will use the audio stream from SVXlink via UDP. 

It is stated in the svxlink manual that audio_dev should be defined
audio_dev = udp:127.0.0.1:10001

SVXlink has in [GLOBAL]
CARD_CHANNELS = 1
CARD_SAMPLE_RATE = 48000

Part of TX 
[TxUDP]
audio_dev =udp:127.0.0.1:10001
....

when it monitors the UDP broadcast stream on that port
I can see the stream being sent but the packets are 2016 bytes in size

If the audio is 48,000kHz with 20ms chunk, 16bit, mono
That should give 48000 * 0.02 = 960 samples per chunk = 1920 bytes
Why does SVXlink send 2016 bytes, according to calculations it should be 1920 bytes?

The question is because the audio quality detected via UDP from svxlink is definitely worse than it is used with audo_dev = alas: plughw: loopback, 0.2

When audio is sent via UDP to svxlink in a packet size of 1920 bytes the quality of the received audio is good.
Svxlink has in [RxUDP] audio_dev = udp: 127.0.0.1: 10002

**Comment by sm0svx** [comment]
The packet size depend on the block size used inside of SvxLink and since most sound cards have buffers that are like 256, 512 or 1024 bytes in size, the UDP "audio device" also use these sizes. For 48k sample rate the buffer size (hint) is 1024 bytes. The UDP code will actually recalculate that size to a number that give an integer millisecond packet size for some reason that I don't remember right now.

```
int pace_interval = 1000 * block_size_hint / sampleRate();
block_size = pace_interval * sampleRate() / 1000;
```
The pace_interval will be rounded to 21ms and the block_size will then end up being 1008 samples = 2016 bytes.

I'll close this issue since it does not seem to be a bug. Open it again if you still think it is.
