### ISSUE TITLE
reflector has problems with burst tones nearby 1750Hz

### ISSUE THREAD

**Issue by IngoTB303** [sm0svx/svxlink#627]
Since I installed the svxupdate, my YAESU devices cannot open the repeater with the 1750Hz tone anymore. I measured a frequency of 1736Hz which is only 16Hz nearby. The bandwith around the 1750Hz tone should be higher, e.g. +- 25Hz.
Thanks and best regards, Ingo

**Comment by dl8bby** [comment]
It seems to be a general problem that Yaesu C4FM/FM handhelds only transmit a tone burst of 1736 Hz. This was not a problem with older Svx versions, the decoder bandwidth was 50 Hz. With Svx version 1.7.99.54, the bandwidth has been reduced to 25 Hz, so that C4FM/FM handhelds can no longer open repeaters with a tone call. However, a return to 50 Hz bandwidth is not necessary, a detector bandwidth of 35 Hz would be a good compromise. A tone call of 1736 Hz is then within the bandwidth and could open the repeaters (tested with a modified RepeaterLogic.cpp).
73, Matthias DL8BBY
