### ISSUE TITLE
Using hamlib to control the transceiver [sf#14]

### ISSUE THREAD

**Issue by sm0svx** [sm0svx/svxlink#69]
**Reported by f4ecw on 2011-06-14 20:19 UTC**
Do you use hamlib to control the receiver ? It has a nice interface to many different radios.
http://hamlib.org

**Comment by petrkr** [comment]
almost 11 years after... I trying to set up Link version of svxlink and I looking for how to PTT by using hamlib, so I found this one.

I am using daemon version of rigctld to read status from radio so I can not use RTS/DTR serial line for svxlink as that serial port is occpuied by rigctld already.

How I can workaround it so svxlink can control PTT over hamlib too?

**Comment by sm0svx** [comment]
Have a look at this [Python script](https://raw.githubusercontent.com/sm0svx/svxlink/refs/heads/master/src/svxlink/scripts/trx_pty_ctrl.py) which use the SvxLink SQL/PTT PTY feature to implement transceiver control.

It should be possible to implement a class that use hamlib instead of talking to the GCOM16 transceiver.

**Comment by petrkr** [comment]
> Have a look at this [Python script](https://raw.githubusercontent.com/sm0svx/svxlink/refs/heads/master/src/svxlink/scripts/trx_pty_ctrl.py) which use the SvxLink SQL/PTT PTY feature to implement transceiver control.
> 
> It should be possible to implement a class that use hamlib instead of talking to the GCOM16 transceiver.

Good to know about PTY... Have to check it..

This script using already 5 years deprecated python2, which is no longer available on new systems.. But it would be nice start for inspiration to write something for python3.11

Thanks.

I have to also somehow solve stop/start of svxlink itself (deletion / creation of pty file).


But if there is already any known systemd service, then it would save lot of "developing wheel again" time.

Otherwise I will do some svxlink / hamlib bridge in python and publish at mine github

**Comment by petrkr** [comment]
Some proof-of-concept https://github.com/petrkr/rigremote/blob/develop/svxlink-hamlib-bridge.py
