### ISSUE TITLE
Refresh echolink directory server information before rejecting the incoming connection

### ISSUE THREAD

**Issue by dranch** [sm0svx/svxlink#93]
From time to time, I see people trying to connect to me but Svxlink refuses to allow the connect:
```
*** WARNING: Ignoring incoming connection from WA6TJQ since the IP address
registered in the directory server (199.68.199.69) is not the same as the
remote IP address (199.68.199.63) of the incoming connection
```

Per Tobias on the svxlink-devel list:
> I would not recommend this (using "ALLOW_IP=0.0.0.0/0") since anyone can connect. No EchoLink
> registration is required. The ALLOW_IP option was added to allow connections on an internal private
> network.
>
> I believe the correct solution is to refresh the directory server information before rejecting the
> connection. It's probably the cached information that is wrong, not the information in the EchoLink
> directory servers.

**Comment by granitepenguin** [comment]
Using branch issue93 appears to work.

Wed Apr 29 13:07:59 2015: SvxLink v1.4.99.0 (Apr 29 2015) Copyright (C)
2003-2014 Tobias Blomberg / SM0SVX


I still see a few of these errors (8 in this case, only 2 in another):

  Wed Apr 29 13:12:27 2015: *** WARNING: Ignoring incoming connection from
  K9DWR since the IP address registered in the directory server
  (107.23.11.57) is not the same as the remote IP address (107.23.158.3)
  of the incoming connection

But instead of it continuing to do that, it now continues as expected 
and eventually connects with the new IP address:

  Wed Apr 29 13:12:27 2015: Spurious audio packet received from
  107.23.158.3
  Wed Apr 29 13:12:29 2015: Incoming EchoLink connection from K9DWR
  (David) at 107.23.158.3
  Wed Apr 29 13:12:29 2015: EchoLink: Using GSM codec only
  Wed Apr 29 13:12:29 2015: SimplexLogic: Activating module EchoLink...
