### ISSUE TITLE
Request: Voter info to external file or TCL function

### ISSUE THREAD

**Issue by ghost** [sm0svx/svxlink#99]
We would like to interface the receiver information of the repeater to a website and/or app so the
users can see on which receiver they are incoming.  The other co-channel group in the Netherlands
has that too, and apparently it is being appreciated.
For example, the Voter could write a status file in a configurable path, that I would put in /dev/shm,
where it writes a line of status information every time it has new information (changed Rx SIGLEV,
squelch opened/closed, switched to another receiver, etc).  That line could e.g. be formatted like this:
YYYY-MM-DD HH:MM:SS.mmm Receiver1=siglev#\* Receiver2=siglev# Receiver3=siglev
2014-09-04 10:46:23.431 Receiver1=22.334#\* Receiver2=89.422# Receiver3=3.342
(the \* would indicate that Receiver1 is active at that time, # indicates the squelch is open)
The line would be overwritten each time, C code that I normally use for that:
        rewind(statfile);
        fprintf(statfile,".....",...);
        fflush(statfile);
        ftruncate(fileno(statfile),ftell(statfile));
The webserver then has to poll this file to get the information when a user requests it.

Alternative implementation: the Voter could be extended to call a TCL function whenever it has
new updated status.  The user can then write a TCL function to create a file like that or provide
another IPC mechanism to the receiving application.   May be more CPU intensive.

**Comment by pe1chl** [comment]
Ok that sounds reasonable.   What kind of polling interval are you implementing?
My daemon (which faces the problem of "is svxlink already running or maybe restarting")
handles the problem from the other side by trying the open of the pty slave and when it
fails it tries every 10 seconds.  It never sends data to the pty but only listens for new
incoming data, without any timeout because data only arrives when the squelch is open,
which of course may not happen for undetermined lengths of time.
When it reads EOF it closes the pty, waits 5 seconds and then goes into the open-loop
again.

**Comment by sm0svx** [comment]
The polling interval is set to 100ms right now but as soon as you open the device it's back to using an FdWatch. The device is not being closed inbetween polls so the polling should not interfere with what you are doing.

**Comment by pe1chl** [comment]
Ok 100ms should be fine.   I was thinking about seconds...tens of seconds.
